# Generated by Django 4.1.5 on 2023-04-07 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(verbose_name='ID_user')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'billing"."customer',
            },
        ),
        migrations.CreateModel(
            name='PrivilegedRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'created'), ('subscribe', 'subscribe'), ('expired', 'expired'), ('blocked', 'blocked')], max_length=10, verbose_name='Status')),
                ('role_payment', models.CharField(max_length=255, verbose_name='Role')),
                ('end_payment', models.DateTimeField(verbose_name='End payment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.customer', verbose_name='customers')),
            ],
            options={
                'verbose_name': 'privileged_role',
                'verbose_name_plural': 'privileged_roles',
                'db_table': 'billing"."privileged_role',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('billed', 'billed'), ('paid', 'paid'), ('billed_timeout', 'billed_timeout'), ('refund', 'refund'), ('refunded', 'refunded')], max_length=15, verbose_name='Status')),
                ('role_payment', models.CharField(max_length=255, verbose_name='Role')),
                ('amount_months', models.IntegerField(verbose_name='Months')),
                ('payed_at', models.DateTimeField(verbose_name='Payed')),
                ('personal_discount', models.IntegerField(blank=True, null=True, verbose_name='Personal discount')),
                ('months_discount', models.IntegerField(blank=True, null=True, verbose_name='Months discount')),
                ('promocode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Promocode')),
                ('tariff', models.FloatField(verbose_name='Price')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('currency', models.CharField(max_length=255, verbose_name='Currency')),
                ('id_payment', models.TextField(blank=True, null=True, verbose_name='id_payment')),
                ('id_checkout', models.TextField(blank=True, null=True, verbose_name='id_checkout')),
                ('id_refund', models.TextField(blank=True, null=True, verbose_name='id_refund')),
                ('card', models.TextField(blank=True, null=True, verbose_name='card')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.customer', verbose_name='customers')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'billing"."payment',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user_id'], name='user_id_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('user_id', 'email'), name='customer_unique'),
        ),
    ]
