# Generated by Django 4.1.5 on 2023-04-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='customer_payment_idx',
        ),
        migrations.RemoveConstraint(
            model_name='privilegedrole',
            name='customer_role_idx',
        ),
    ]
