# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roles_control.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13roles_control.proto\x12\x0crolescontrol\"\x19\n\x08UserInfo\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x17\n\x07NewRole\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x04Role\x12\x0f\n\x07role_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"K\n\x0bProvideRole\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07role_id\x18\x02 \x01(\t\x12\x1a\n\x12jti_to_compromised\x18\x03 \x01(\t\"\x12\n\x04Uuid\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x0fOperationResult\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\x32\xe6\x02\n\x0cRolesControl\x12;\n\x0bGetUserInfo\x12\x12.rolescontrol.Uuid\x1a\x16.rolescontrol.UserInfo\"\x00\x12\x39\n\nCreateRole\x12\x15.rolescontrol.NewRole\x1a\x12.rolescontrol.Uuid\"\x00\x12\x41\n\nUpdateRole\x12\x12.rolescontrol.Role\x1a\x1d.rolescontrol.OperationResult\"\x00\x12M\n\x0fProvideRoleUser\x12\x19.rolescontrol.ProvideRole\x1a\x1d.rolescontrol.OperationResult\"\x00\x12L\n\x0eRevokeRoleUser\x12\x19.rolescontrol.ProvideRole\x1a\x1d.rolescontrol.OperationResult\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'roles_control_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERINFO._serialized_start=37
  _USERINFO._serialized_end=62
  _NEWROLE._serialized_start=64
  _NEWROLE._serialized_end=87
  _ROLE._serialized_start=89
  _ROLE._serialized_end=126
  _PROVIDEROLE._serialized_start=128
  _PROVIDEROLE._serialized_end=203
  _UUID._serialized_start=205
  _UUID._serialized_end=223
  _OPERATIONRESULT._serialized_start=225
  _OPERATIONRESULT._serialized_end=262
  _ROLESCONTROL._serialized_start=265
  _ROLESCONTROL._serialized_end=623
# @@protoc_insertion_point(module_scope)
