CREATE SCHEMA "marketing";

CREATE SCHEMA "payment";

CREATE TABLE "marketing"."discount" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" uuid,
  "discount" int
);

CREATE TABLE "marketing"."promo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar,
  "description" text,
  "role" varchar,
  "discount" int
);

CREATE TABLE "marketing"."tariff" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar,
  "description" text,
  "price" float
);

CREATE TABLE "payment"."user" (
  "id" uuid PRIMARY KEY,
  "email" varchar,
  "state" varchar,
  "role_payed" varchar,
  "payed_at" timestamp,
  "end_pay" timestamp,
  "discount" int,
  "promo_code" text,
  "id_pay" text,
  "card" text
);
