# Generated by Django 4.1.5 on 2023-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthsDiscount',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('amount_months', models.IntegerField(verbose_name='Months')),
                ('discount', models.IntegerField(verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'months_discount',
                'verbose_name_plural': 'months_discounts',
                'db_table': 'marketing"."months_discount',
            },
        ),
        migrations.CreateModel(
            name='PersonalDiscount',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True, verbose_name='ID_user')),
                ('discount', models.IntegerField(verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'personal_discount',
                'verbose_name_plural': 'personal_discounts',
                'db_table': 'marketing"."personal_discount',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, verbose_name='Promocode')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('discount', models.IntegerField(verbose_name='Discount')),
                ('amount_months', models.IntegerField(verbose_name='Months')),
                ('expiration', models.DateTimeField(verbose_name='Expiration')),
            ],
            options={
                'verbose_name': 'promocode',
                'verbose_name_plural': 'promocodes',
                'db_table': 'marketing"."promocode',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('auth_role_id', models.UUIDField(unique=True, verbose_name='ID_auth_role')),
            ],
            options={
                'verbose_name': 'tariff',
                'verbose_name_plural': 'tariffs',
                'db_table': 'marketing"."tariff',
            },
        ),
        migrations.AddConstraint(
            model_name='personaldiscount',
            constraint=models.UniqueConstraint(fields=('user_id',), name='personal_discount_unique'),
        ),
    ]
