# Generated by Django 4.1.5 on 2023-04-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='auth_role_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID_auth_role'),
        ),
    ]
