# Generated by Django 4.1.5 on 2023-04-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='monthsdiscount',
            index=models.Index(fields=['amount_months'], name='amount_months_discount_idx'),
        ),
        migrations.AddIndex(
            model_name='personaldiscount',
            index=models.Index(fields=['user_id'], name='user_id_personal_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='code_promocode_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['role'], name='role_tariff_idx'),
        ),
    ]
