# Generated by Django 4.1.5 on 2023-04-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_monthsdiscount_amount_months_discount_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthsdiscount',
            name='amount_months_discount_idx',
        ),
        migrations.RemoveIndex(
            model_name='personaldiscount',
            name='user_id_personal_idx',
        ),
        migrations.RemoveIndex(
            model_name='promocode',
            name='code_promocode_idx',
        ),
        migrations.RemoveIndex(
            model_name='tariff',
            name='role_tariff_idx',
        ),
    ]
