name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.10"]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml types-requests mypy flake8 wemake-python-styleguide flake8-html
        pip install -r billing-api/requirements.txt
        pip install -r admin-billing/requirements.txt
        pip install pre-commit

    - name: Create report directories
      run: |
        mkdir -p reports/styleguide_reports/billing-api
        mkdir -p reports/styleguide_reports/admin-billing

    - name: Run flake8/styleguide
      run: |
        flake8 billing-api --config=setup.cfg --exit-zero --format=html --htmldir=reports/styleguide_reports/billing-api
        flake8 admin-billing --config=setup.cfg --exit-zero --format=html --htmldir=reports/styleguide_reports/admin-billing
        
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: reports/
